#!/usr/bin/python3

import subprocess

from qutescript import userscript

# for bookmarklet in firefox or whatever
# org-protocol://capture?template=b&url='+encodeURIComponent(location.href)+'&title='+encodeURIComponent(document.title)+'&body='+encodeURIComponent(window.getSelection())

@userscript
def org_capture(request):
    protocol_link = "org-protocol://capture?template=b&url={url}&title={title}&body={body}".format(
        url = request.url,
        title = request.title,
        body = request.selected_text
    )
    subprocess.call(['emacsclient', '-c', '-F', '(quote (name . "org-protocol-capture"))', protocol_link])


if __name__ == '__main__':
    org_capture()
